package view;

import controller.MainLogic;
import controller.Tool;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.RoomCategory;

/**
 *
 * @author kappe
 */
public class AddRoomCategoryFrame extends javax.swing.JFrame {

    private final MainFrame parentFrame;
    private final MainLogic app;
    private static final Logger LOG = Logger.getLogger(AddRoomCategoryFrame.class.getName());

    /**
     * Creates new form AddRoomCategoryFrame
     *
     * @param parentFrame
     */
    public AddRoomCategoryFrame(MainFrame parentFrame) {
        initComponents();

        this.parentFrame = parentFrame;
        this.app = parentFrame.app;
    }

    private void clearAllFields() {
        descriptionFld.setText("");
        priceFld.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionFld = new javax.swing.JTextArea();
        priceFld = new javax.swing.JTextField();
        titleLbl = new javax.swing.JLabel();
        descriptionLbl = new javax.swing.JLabel();
        priceLbl = new javax.swing.JLabel();
        euroSignLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pridať novú kategóriu izieb");
        setMinimumSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(204, 171, 244));
        mainPanel.setMinimumSize(new java.awt.Dimension(700, 500));
        mainPanel.setPreferredSize(new java.awt.Dimension(700, 500));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtn.setBackground(new java.awt.Color(114, 14, 126));
        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("<html>\n<p style=\"text-align: center;\">\nSpäť\n</p>\n</html>");
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                backBtnMouseReleased(evt);
            }
        });
        mainPanel.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 100, 40));

        addBtn.setBackground(new java.awt.Color(114, 14, 126));
        addBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("<html>\n<p style=\"text-align: center;\">\nPridať\n</p>\n</html>");
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                addBtnMouseReleased(evt);
            }
        });
        mainPanel.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 100, 40));

        descriptionFld.setColumns(20);
        descriptionFld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descriptionFld.setRows(5);
        jScrollPane1.setViewportView(descriptionFld);

        mainPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 290, 140));

        priceFld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        priceFld.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        mainPanel.add(priceFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 90, 30));

        titleLbl.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 0, 0));
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("Vyplňte údaje o novej kategórií");
        mainPanel.add(titleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 700, 50));

        descriptionLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        descriptionLbl.setForeground(new java.awt.Color(114, 14, 126));
        descriptionLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        descriptionLbl.setText("Popis novej kategórie:");
        mainPanel.add(descriptionLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 200, 30));

        priceLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        priceLbl.setForeground(new java.awt.Color(114, 14, 126));
        priceLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        priceLbl.setText("Cena novej kategórie:");
        mainPanel.add(priceLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 200, 30));

        euroSignLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        euroSignLbl.setForeground(new java.awt.Color(114, 14, 126));
        euroSignLbl.setText("€");
        mainPanel.add(euroSignLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 190, 30));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseReleased
        this.parentFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnMouseReleased

    private void addBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseReleased
        if (descriptionFld.getText().isBlank() || priceFld.getText().isBlank()) {
            LOG.log(Level.WARNING, "Nesprávny vstup: Neboli vyplnené všetky údaje pre kategóriu izby.\n");
            JOptionPane.showMessageDialog(null, "Prosím vyplnte všetky údaje.", "Chýbajúce údaje!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Double price = Tool.getPrice(priceFld);
        String description = descriptionFld.getText().trim();

        if (price < 0) {
            LOG.log(Level.WARNING, "Nesprávny vstup: Záporná cena kategórie izby.\n");
            return;
        }

        app.addRoomCategory(new RoomCategory(price, description));
        JOptionPane.showMessageDialog(null, "Nová kategória bola úspešne uložená.");
        clearAllFields();
    }//GEN-LAST:event_addBtnMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextArea descriptionFld;
    private javax.swing.JLabel descriptionLbl;
    private javax.swing.JLabel euroSignLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField priceFld;
    private javax.swing.JLabel priceLbl;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
