package view;

import controller.MainLogic;
import java.io.File;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import model.Room;
import model.RoomCategory;

/**
 *
 * @author kappe
 */
public class AddRoomFrame extends javax.swing.JFrame {

    private final MainFrame parentFrame;
    private final MainLogic app;
    private static final Logger LOG = Logger.getLogger(AddRoomFrame.class.getName());

    /**
     * Creates new form AddRoomFrame
     *
     * @param parentFrame
     */
    public AddRoomFrame(MainFrame parentFrame) {
        initComponents();

        this.parentFrame = parentFrame;
        this.app = parentFrame.app;

        populateCategoryComboBox();
    }

    private void populateCategoryComboBox() {
        String[] descriptions = app.getRoomCategoriesDsescription();
        categoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(descriptions));

        if (categoryComboBox.getModel().getSize() > 0) {
            categoryComboBox.setSelectedIndex(0);
        }
    }

    // Pridat do zoznamu cestu k obrazku
    private void appendToList(String picturePath) {
        DefaultListModel<String> newModel = new DefaultListModel<>();
        ListModel<String> oldModel = picturesLst.getModel();

        for (int i = 0; i < oldModel.getSize(); i++) {
            newModel.add(i, oldModel.getElementAt(i));
        }

        newModel.add(oldModel.getSize(), picturePath);
        picturesLst.setModel(newModel);
    }

    // Odstranit zo zoznamu cestu k obrazku
    private void removeFromList() {
        int selectedIndex = picturesLst.getSelectedIndex();

        if (selectedIndex < 0) {
            return;
        }

        DefaultListModel<String> newModel = new DefaultListModel<>();
        ListModel<String> oldModel = picturesLst.getModel();

        for (int i = 0, counter = 0; i < oldModel.getSize(); i++) {
            if (i != selectedIndex) {
                newModel.add(counter++, oldModel.getElementAt(i));
            }
        }

        picturesLst.setModel(newModel);
    }

    private ArrayList<ImageIcon> getPictures() {
        ArrayList<ImageIcon> pictures = new ArrayList<>();
        ListModel<String> model = picturesLst.getModel();

        for (int i = 0; i < model.getSize(); i++) {
            pictures.add(new ImageIcon(model.getElementAt(i)));
        }

        return pictures;
    }

    private void clearAllFields() {
        idFld.setText("");
        noteFld.setText("");
        categoryComboBox.setSelectedIndex(0);
        if (picturesLst.getModel().getSize() > 0) {
            ((DefaultListModel) picturesLst.getModel()).removeAllElements();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        createBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        idFld = new javax.swing.JTextField();
        noteFld = new javax.swing.JTextField();
        categoryComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        picturesLst = new javax.swing.JList<>();
        titleLbl = new javax.swing.JLabel();
        galleryLbl = new javax.swing.JLabel();
        categoryLbl = new javax.swing.JLabel();
        idLbl = new javax.swing.JLabel();
        noteLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pridať novú izbu");
        setResizable(false);
        setSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(204, 171, 244));
        mainPanel.setMinimumSize(new java.awt.Dimension(700, 500));
        mainPanel.setPreferredSize(new java.awt.Dimension(700, 500));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtn.setBackground(new java.awt.Color(114, 14, 126));
        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("<html>\n<p style=\"text-align: center;\">\nSpäť\n</p>\n</html>");
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                backBtnMouseReleased(evt);
            }
        });
        mainPanel.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 100, 40));

        createBtn.setBackground(new java.awt.Color(114, 14, 126));
        createBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        createBtn.setForeground(new java.awt.Color(255, 255, 255));
        createBtn.setText("<html>\n<p style=\"text-align: center;\">\nVytvoriť\n</p>\n</html>");
        createBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                createBtnMouseReleased(evt);
            }
        });
        mainPanel.add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 100, 40));

        addBtn.setBackground(new java.awt.Color(114, 14, 126));
        addBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("<html>\n<p style=\"text-align: center;\">\nPridať\n</p>\n</html>");
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                addBtnMouseReleased(evt);
            }
        });
        mainPanel.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 100, 30));

        deleteBtn.setBackground(new java.awt.Color(114, 14, 126));
        deleteBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("<html>\n<p style=\"text-align: center;\">\nOdstrániť\n</p>\n</html>");
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                deleteBtnMouseReleased(evt);
            }
        });
        mainPanel.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 100, 30));

        idFld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mainPanel.add(idFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 290, 30));

        noteFld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mainPanel.add(noteFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 290, 30));

        categoryComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        categoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2" }));
        mainPanel.add(categoryComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 290, 30));

        picturesLst.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        picturesLst.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(picturesLst);

        mainPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 290, 170));

        titleLbl.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 0, 0));
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("Vyplňte údaje o novej izbe");
        mainPanel.add(titleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 700, 50));

        galleryLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        galleryLbl.setForeground(new java.awt.Color(114, 14, 126));
        galleryLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        galleryLbl.setText("Obrázky o izbe:");
        mainPanel.add(galleryLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 150, 30));

        categoryLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        categoryLbl.setForeground(new java.awt.Color(114, 14, 126));
        categoryLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        categoryLbl.setText("Kategória izby:");
        mainPanel.add(categoryLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 150, 30));

        idLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        idLbl.setForeground(new java.awt.Color(114, 14, 126));
        idLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        idLbl.setText("Číslo izby:");
        mainPanel.add(idLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 150, 30));

        noteLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        noteLbl.setForeground(new java.awt.Color(114, 14, 126));
        noteLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        noteLbl.setText("Poznámka:");
        mainPanel.add(noteLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 150, 30));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseReleased
        this.parentFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnMouseReleased

    private void createBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createBtnMouseReleased
        if (categoryComboBox.getModel().getSize() <= 0) {
            LOG.log(Level.WARNING, "Nesprávny vstup: Nebola vybraná kategória novej izby.\n");
            JOptionPane.showMessageDialog(null, "Vytvorte novú kategóriu izby.", "Neexistujúca kategória izby!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (idFld.getText().isBlank()) {
            LOG.log(Level.WARNING, "Nesprávny vstup: Chýba ID pre novú izbu.\n");
            JOptionPane.showMessageDialog(null, "Prosím zadajte číslo izby.", "Chýbajúce údaje!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String roomID = idFld.getText().trim();

        if (!Room.isUniqueID(app.getRooms(), roomID)) {
            LOG.log(Level.WARNING, "Nesprávny vstup: Zvolené ID už existuje.\n");
            JOptionPane.showMessageDialog(null, "Izba s rovnakým číslom už existuje.", "Chýbné číslo izby!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String note = noteFld.getText().trim();
        RoomCategory category = app.getSelectedRoomCategory(categoryComboBox.getSelectedIndex());
        ArrayList<ImageIcon> pictures = getPictures();

        app.addRoom(new Room(roomID, note, category, pictures));
        JOptionPane.showMessageDialog(null, "Nová izba bola úspešne vytvorená.");
        clearAllFields();
    }//GEN-LAST:event_createBtnMouseReleased

    private void addBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseReleased
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File(System.getProperty("user.dir")));
        chooser.showOpenDialog(this);

        File f = chooser.getSelectedFile();
        if (f == null) {
            return;
        }

        if (f.getName().endsWith(".jpg") || f.getName().endsWith(".jpeg") || f.getName().endsWith(".png")) {
            appendToList(f.getAbsolutePath());
        } else {
            LOG.log(Level.WARNING, "Nesprávny typ súboru: Vybraný súbor nie je správneho typu.\n");
            JOptionPane.showMessageDialog(null, "Prosím vyberte súbor typu jpg, jpeg alebo png.", "Nesprávny formát obrázku!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addBtnMouseReleased

    private void deleteBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseReleased
        removeFromList();
    }//GEN-LAST:event_deleteBtnMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox<String> categoryComboBox;
    private javax.swing.JLabel categoryLbl;
    private javax.swing.JButton createBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel galleryLbl;
    private javax.swing.JTextField idFld;
    private javax.swing.JLabel idLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField noteFld;
    private javax.swing.JLabel noteLbl;
    private javax.swing.JList<String> picturesLst;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
