package view;

import controller.MainLogic;
import controller.Tool;
import java.awt.Color;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.Reservation;

/**
 *
 * @author kappe
 */
public class CancelReservationFrame extends javax.swing.JFrame {

    private final MainFrame parentFrame;
    private final MainLogic app;

    /**
     * Creates new form CancelReservationFrame
     *
     * @param parentFrame
     */
    public CancelReservationFrame(MainFrame parentFrame) {
        initComponents();

        this.parentFrame = parentFrame;
        this.app = parentFrame.app;

        populateReservationsTable();
    }

    private void populateReservationsTable() {
        DefaultTableModel tblModel = (DefaultTableModel) reservationsTbl.getModel();
        tblModel.setRowCount(0);
        DecimalFormat formatter = new DecimalFormat("########0.00");

        ArrayList<Reservation> reservations = app.getReservations();
        for (int i = 0; i < reservations.size(); i++) {
            Reservation r = reservations.get(i);

            String[] row = {r.getClient().getName(), r.getRoom().getId(), formatter.format(r.getPrice()) + " €",
                Tool.dateToString(r.getFrom()), Tool.dateToString(r.getUntil())};
            tblModel.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reservationsTbl = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Zrušenie rezervácie");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(204, 171, 244));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLbl.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 0, 0));
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("Vyberte rezerváciu na zrušenie");
        mainPanel.add(titleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 700, 50));

        reservationsTbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        reservationsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Zákazník", "Izba", "Cena", "Dátum od", "Dátum do"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        reservationsTbl.setRowHeight(22);
        reservationsTbl.setSelectionBackground(new java.awt.Color(204, 0, 204));
        reservationsTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(reservationsTbl);
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setHorizontalAlignment(JLabel.CENTER);
        headerRenderer.setBackground(new Color(114, 14, 126));
        headerRenderer.setForeground(new Color(255, 255, 255));

        for (int i = 0; i < reservationsTbl.getModel().getColumnCount(); i++) {
            reservationsTbl.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }

        mainPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 650, 300));

        backBtn.setBackground(new java.awt.Color(114, 14, 126));
        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("<html>\n<p style=\"text-align: center;\">\nSpäť\n</p>\n</html>");
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                backBtnMouseReleased(evt);
            }
        });
        mainPanel.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 110, 40));

        cancelBtn.setBackground(new java.awt.Color(114, 14, 126));
        cancelBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("<html>\n<p style=\"text-align: center;\">\nZrušiť\n</p>\n</html>");
        cancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cancelBtnMouseReleased(evt);
            }
        });
        mainPanel.add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 110, 40));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseReleased
        this.parentFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnMouseReleased

    private void cancelBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseReleased
        int selectedIndex = reservationsTbl.getSelectedRow();

        if (selectedIndex < 0) {
            JOptionPane.showMessageDialog(null, "Vyberte ktorú rezerváciu chcete zrušiť.", "Chyba!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        app.removeReservation(selectedIndex);
        JOptionPane.showMessageDialog(null, "Rezervácia bola zrušená.");
        populateReservationsTable();
    }//GEN-LAST:event_cancelBtnMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTable reservationsTbl;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
