package view;

import controller.MainLogic;
import controller.Tool;
import java.awt.Color;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.Accommodation;
import model.Client;
import model.Reservation;
import model.Room;

/**
 *
 * @author kappe
 */
public class CreateReservationFrame extends javax.swing.JFrame {

    private final MainFrame parentFrame;
    private final MainLogic app;
    private ArrayList<Room> availableRooms;
    private Date fromDate;
    private Date untilDate;
    private static final Logger LOG = Logger.getLogger(CreateReservationFrame.class.getName());

    /**
     * Creates new form MakeReservationFrame
     *
     * @param parentFrame
     */
    public CreateReservationFrame(MainFrame parentFrame) {
        initComponents();

        this.parentFrame = parentFrame;
        this.app = parentFrame.app;

        populateClientComboBox();
    }

    private void populateClientComboBox() {
        String[] clients = app.getClientsDescription();
        clientComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(clients));

        if (clientComboBox.getModel().getSize() > 0) {
            clientComboBox.setSelectedIndex(0);
        }
    }

    private void populateAvailalbeReservationsTable() {
        DefaultTableModel tblModel = (DefaultTableModel) availableReservationsTbl.getModel();
        tblModel.setRowCount(0);
        DecimalFormat formatter = new DecimalFormat("########0.00");

        for (int i = 0; i < availableRooms.size(); i++) {
            Room r = availableRooms.get(i);
            Double price = r.calculatePrice(fromDate, untilDate);

            String[] row = {r.getId(), r.getCategory().toString(), formatter.format(price) + " €"};
            tblModel.addRow(row);
        }
    }

    private void setAvailableRooms() {
        availableRooms = (ArrayList<Room>) app.getRooms().clone();
        Iterator<Room> roomIterator;
        String reservationRoomId;

        for (Reservation reservation : app.getReservations()) {

            if (!(Tool.isBefore(untilDate, reservation.getFrom()) || Tool.isAfter(fromDate, reservation.getUntil()))) {
                reservationRoomId = reservation.getRoom().getId();
                roomIterator = availableRooms.iterator();

                while (roomIterator.hasNext()) {
                    Room room = roomIterator.next();
                    if (room.getId().equals(reservationRoomId)) {
                        roomIterator.remove();
                        break;
                    }
                }
            }
        }

        for (Accommodation accommodation : app.getAccommodations()) {

            if (!(Tool.isBefore(untilDate, accommodation.getFrom()) || Tool.isAfter(fromDate, accommodation.getUntil()))) {
                reservationRoomId = accommodation.getRoom().getId();
                roomIterator = availableRooms.iterator();

                while (roomIterator.hasNext()) {
                    Room room = roomIterator.next();
                    if (room.getId().equals(reservationRoomId)) {
                        roomIterator.remove();
                        break;
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        clientComboBox = new javax.swing.JComboBox<>();
        reserveBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        showBtn = new javax.swing.JButton();
        fromDateChooser = new com.toedter.calendar.JDateChooser();
        untilDateChooser = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        availableReservationsTbl = new javax.swing.JTable();
        fromLbl = new javax.swing.JLabel();
        titleLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        untilLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tvorba rezervácie");
        setMinimumSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(204, 171, 244));
        mainPanel.setMinimumSize(new java.awt.Dimension(710, 510));
        mainPanel.setPreferredSize(new java.awt.Dimension(710, 510));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clientComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clientComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2" }));
        mainPanel.add(clientComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 420, 30));

        reserveBtn.setBackground(new java.awt.Color(114, 14, 126));
        reserveBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reserveBtn.setForeground(new java.awt.Color(255, 255, 255));
        reserveBtn.setText("<html>\n<p style=\"text-align: center;\">\nRezervovať\n</p>\n</html>");
        reserveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                reserveBtnMouseReleased(evt);
            }
        });
        mainPanel.add(reserveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 110, 40));

        backBtn.setBackground(new java.awt.Color(114, 14, 126));
        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("<html>\n<p style=\"text-align: center;\">\nSpäť\n</p>\n</html>");
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                backBtnMouseReleased(evt);
            }
        });
        mainPanel.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 110, 40));

        showBtn.setBackground(new java.awt.Color(114, 14, 126));
        showBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        showBtn.setForeground(new java.awt.Color(255, 255, 255));
        showBtn.setText("<html>\n<p style=\"text-align: center;\">\nZobraziť dostupné izby\n</p>\n</html>");
        showBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                showBtnMouseReleased(evt);
            }
        });
        mainPanel.add(showBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 230, 30));
        mainPanel.add(fromDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 180, -1));
        mainPanel.add(untilDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 180, -1));

        availableReservationsTbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        availableReservationsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Izba", "Kategória", "Cena"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        availableReservationsTbl.setRowHeight(22);
        availableReservationsTbl.setSelectionBackground(new java.awt.Color(204, 0, 204));
        availableReservationsTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(availableReservationsTbl);
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setHorizontalAlignment(JLabel.CENTER);
        headerRenderer.setBackground(new Color(114, 14, 126));
        headerRenderer.setForeground(new Color(255, 255, 255));

        for (int i = 0; i < availableReservationsTbl.getModel().getColumnCount(); i++) {
            availableReservationsTbl.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }

        mainPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 610, 150));

        fromLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fromLbl.setForeground(new java.awt.Color(144, 14, 126));
        fromLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fromLbl.setText("Od:");
        mainPanel.add(fromLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 30, 30));

        titleLbl.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 0, 0));
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("Vyplňte údaje o rezervácií");
        mainPanel.add(titleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 700, 50));

        nameLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nameLbl.setForeground(new java.awt.Color(144, 14, 126));
        nameLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nameLbl.setText("Meno zákazníka:");
        mainPanel.add(nameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 150, 30));

        untilLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        untilLbl.setForeground(new java.awt.Color(144, 14, 126));
        untilLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        untilLbl.setText("Do:");
        mainPanel.add(untilLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 30, 30));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseReleased
        this.parentFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnMouseReleased

    private void showBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showBtnMouseReleased
        fromDate = fromDateChooser.getDate();
        untilDate = untilDateChooser.getDate();

        if (fromDate == null || untilDate == null) {
            LOG.log(Level.WARNING, "Nesprávny vstup: Chýba dátum rezervácie.\n");
            JOptionPane.showMessageDialog(null, "Prosím vyberte si dátum pre rezerváciu.", "Chybný dátum!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!Tool.isBefore(fromDate, untilDate)) {
            JOptionPane.showMessageDialog(null, "Začiatočný dátum musí byť skôr ako dátum ukončenia.", "Nesprávny termín!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        setAvailableRooms();
        populateAvailalbeReservationsTable();
    }//GEN-LAST:event_showBtnMouseReleased

    private void reserveBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reserveBtnMouseReleased
        int selectedIndex = availableReservationsTbl.getSelectedRow();
        int clientIndex = clientComboBox.getSelectedIndex();

        if (selectedIndex < 0) {
            JOptionPane.showMessageDialog(null, "Prosím vyberte si izbu na rezerváciu.", "Chybná rezervácia", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (clientIndex < 0) {
            JOptionPane.showMessageDialog(null, "Prosím vyberte zákazníka pre rezerváciu.", "Chybná rezervácia", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Client client = app.getSelectedClient(clientIndex);
        Room room = availableRooms.get(selectedIndex);
        double price = room.calculatePrice(fromDate, untilDate);

        app.addReservation(new Reservation(client, room, price, fromDate, untilDate));
        JOptionPane.showMessageDialog(null, "Izba bola úspešne rezervovaná.");
        showBtnMouseReleased(null);
    }//GEN-LAST:event_reserveBtnMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable availableReservationsTbl;
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox<String> clientComboBox;
    private com.toedter.calendar.JDateChooser fromDateChooser;
    private javax.swing.JLabel fromLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JButton reserveBtn;
    private javax.swing.JButton showBtn;
    private javax.swing.JLabel titleLbl;
    private com.toedter.calendar.JDateChooser untilDateChooser;
    private javax.swing.JLabel untilLbl;
    // End of variables declaration//GEN-END:variables
}
