package view;

import controller.MainLogic;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Client;

/**
 *
 * @author kappe
 */
public class CreateClientFrame extends javax.swing.JFrame {

    private final MainFrame parentFrame;
    private final MainLogic app;
    private static final Logger LOG = Logger.getLogger(CreateClientFrame.class.getName());

    /**
     * Creates new form CreateClientFrame
     *
     * @param parentFrame
     */
    public CreateClientFrame(MainFrame parentFrame) {
        initComponents();

        this.parentFrame = parentFrame;
        this.app = parentFrame.app;
    }

    private void clearAllFields() {
        nameFld.setText("");
        mailFld.setText("");
        phoneFld.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        createBtn = new javax.swing.JButton();
        phoneFld = new javax.swing.JTextField();
        nameFld = new javax.swing.JTextField();
        mailFld = new javax.swing.JTextField();
        titleLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        mailLbl = new javax.swing.JLabel();
        phoneLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vytvorenie nového zákazníka");
        setMinimumSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(204, 171, 244));
        mainPanel.setMinimumSize(new java.awt.Dimension(700, 500));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtn.setBackground(new java.awt.Color(114, 14, 126));
        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("<html>\n<p style=\"text-align: center;\">\nSpäť\n</p>\n</html>");
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                backBtnMouseReleased(evt);
            }
        });
        mainPanel.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 100, 40));

        createBtn.setBackground(new java.awt.Color(114, 14, 126));
        createBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        createBtn.setForeground(new java.awt.Color(255, 255, 255));
        createBtn.setText("<html>\n<p style=\"text-align: center;\">\nVytvoriť\n</p>\n</html>");
        createBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                createBtnMouseReleased(evt);
            }
        });
        mainPanel.add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, 100, 40));

        phoneFld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mainPanel.add(phoneFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 290, 30));

        nameFld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mainPanel.add(nameFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 290, 30));

        mailFld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mainPanel.add(mailFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 290, 30));

        titleLbl.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 0, 0));
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("Vyplňte údaje o novom zákazníkovi");
        mainPanel.add(titleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 700, 50));

        nameLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nameLbl.setForeground(new java.awt.Color(114, 14, 126));
        nameLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nameLbl.setText("Meno zákazníka:");
        mainPanel.add(nameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 160, 30));

        mailLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mailLbl.setForeground(new java.awt.Color(114, 14, 126));
        mailLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mailLbl.setText("E-mail:");
        mainPanel.add(mailLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 160, 30));

        phoneLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        phoneLbl.setForeground(new java.awt.Color(114, 14, 126));
        phoneLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        phoneLbl.setText("Telefónne číslo:");
        mainPanel.add(phoneLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 160, 30));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createBtnMouseReleased
        if (nameFld.getText().isBlank() || mailFld.getText().isBlank() || phoneFld.getText().isBlank()) {
            LOG.log(Level.WARNING, "Nesprávny vstup: Chýbajú údaje o novom zákazníkovi.\n");
            JOptionPane.showMessageDialog(null, "Prosím vyplňte všetky údaje.", "Chýbajúce údaje!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String name = nameFld.getText().trim();
        String mail = mailFld.getText().trim();
        String phone = phoneFld.getText().trim();

        if (!Client.isValidEmail(mail)) {
            JOptionPane.showMessageDialog(null, "Email je napísaný v neakceptovateľnom formáte.", "Nesprávny údaj!", JOptionPane.ERROR_MESSAGE);
        } else if (!Client.isValidPhoneNumber(phone)) {
            JOptionPane.showMessageDialog(null, "Telefónne číslo je napísané v neakceptovateľnom formáte.", "Nesprávny údaj!", JOptionPane.ERROR_MESSAGE);
        } else {
            app.addClient(new Client(name, mail, phone));
            JOptionPane.showMessageDialog(null, "Nový zákazník bol úspešne vytvorený.");
            clearAllFields();
        }
    }//GEN-LAST:event_createBtnMouseReleased

    private void backBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseReleased
        this.parentFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton createBtn;
    private javax.swing.JTextField mailFld;
    private javax.swing.JLabel mailLbl;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField nameFld;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField phoneFld;
    private javax.swing.JLabel phoneLbl;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
