package view;

import controller.MainLogic;
import java.awt.Image;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Room;

/**
 *
 * @author kappe
 */
public class EditRoomFrame extends javax.swing.JFrame {

    private final MainFrame parentFrame;
    private final MainLogic app;
    private Room currentRoom;
    private int counter;

    /**
     * Creates new form EditRoomFrame
     *
     * @param parentFrame
     */
    public EditRoomFrame(MainFrame parentFrame) {
        initComponents();

        this.parentFrame = parentFrame;
        this.app = parentFrame.app;

        populateRoomComboBox();
    }

    private void populateRoomComboBox() {
        String[] roomIds = app.getRoomsId();
        roomComboBox.setModel(new DefaultComboBoxModel<>(roomIds));

        if (roomComboBox.getModel().getSize() > 0) {
            roomComboBox.setSelectedIndex(0);
        }
    }

    private void showNextPicture() {
        if (currentRoom.getPictures().size() > 0) {
            Image img = currentRoom.getPictures().get(counter++).getImage();
            counter %= currentRoom.getPictures().size();
            Image imgScale = img.getScaledInstance(picturesLbl.getWidth(), picturesLbl.getHeight(), Image.SCALE_SMOOTH);
            picturesLbl.setIcon(new ImageIcon(imgScale));
        } else {
            picturesLbl.setIcon(null);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        noteFld = new javax.swing.JTextField();
        roomComboBox = new javax.swing.JComboBox<>();
        categoryFld = new javax.swing.JTextField();
        idLbl = new javax.swing.JLabel();
        noteLbl = new javax.swing.JLabel();
        titleLbl = new javax.swing.JLabel();
        categoryLbl = new javax.swing.JLabel();
        galleryLbl = new javax.swing.JLabel();
        picturesLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Upraviť údaje o izbe");
        setResizable(false);
        setSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(204, 171, 244));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtn.setBackground(new java.awt.Color(114, 14, 126));
        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("<html>\n<p style=\"text-align: center;\">\nSpäť\n</p>\n</html>");
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                backBtnMouseReleased(evt);
            }
        });
        mainPanel.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 100, 40));

        nextBtn.setBackground(new java.awt.Color(114, 14, 126));
        nextBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nextBtn.setForeground(new java.awt.Color(255, 255, 255));
        nextBtn.setText("<html>\n<p style=\"text-align: center;\">\nĎalší obrázok\n</p>\n</html>");
        nextBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                nextBtnMouseReleased(evt);
            }
        });
        mainPanel.add(nextBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 140, 30));

        editBtn.setBackground(new java.awt.Color(114, 14, 126));
        editBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editBtn.setForeground(new java.awt.Color(255, 255, 255));
        editBtn.setText("<html>\n<p style=\"text-align: center;\">\nUpraviť\n</p>\n</html>");
        editBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                editBtnMouseReleased(evt);
            }
        });
        mainPanel.add(editBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 100, 40));

        noteFld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mainPanel.add(noteFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 290, 30));

        roomComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        roomComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2" }));
        roomComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomComboBoxActionPerformed(evt);
            }
        });
        mainPanel.add(roomComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 290, 30));

        categoryFld.setEditable(false);
        categoryFld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mainPanel.add(categoryFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 290, 30));

        idLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        idLbl.setForeground(new java.awt.Color(114, 14, 126));
        idLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        idLbl.setText("Číslo izby:");
        mainPanel.add(idLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 140, 30));

        noteLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        noteLbl.setForeground(new java.awt.Color(114, 14, 126));
        noteLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        noteLbl.setText("Poznámka:");
        mainPanel.add(noteLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 140, 30));

        titleLbl.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 0, 0));
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("Upravte údaje o izbe");
        mainPanel.add(titleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 700, 50));

        categoryLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        categoryLbl.setForeground(new java.awt.Color(114, 14, 126));
        categoryLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        categoryLbl.setText("Kategória izby:");
        mainPanel.add(categoryLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 140, 30));

        galleryLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        galleryLbl.setForeground(new java.awt.Color(114, 14, 126));
        galleryLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        galleryLbl.setText("Obrázky o izbe:");
        mainPanel.add(galleryLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 140, 30));

        picturesLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mainPanel.add(picturesLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 290, 170));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseReleased
        this.parentFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnMouseReleased

    private void nextBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextBtnMouseReleased
        showNextPicture();
    }//GEN-LAST:event_nextBtnMouseReleased

    private void editBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseReleased
        currentRoom.setNote(noteFld.getText().trim());
        JOptionPane.showMessageDialog(null, "Údaje boli aktualizované.");
    }//GEN-LAST:event_editBtnMouseReleased

    private void roomComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomComboBoxActionPerformed
        int selectedIndex = roomComboBox.getSelectedIndex();
        this.currentRoom = app.getSelectedRoom(selectedIndex);

        noteFld.setText(currentRoom.getNote());
        categoryFld.setText(currentRoom.getCategory().toString());

        this.counter = 0;
        showNextPicture();
    }//GEN-LAST:event_roomComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField categoryFld;
    private javax.swing.JLabel categoryLbl;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel galleryLbl;
    private javax.swing.JLabel idLbl;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton nextBtn;
    private javax.swing.JTextField noteFld;
    private javax.swing.JLabel noteLbl;
    private javax.swing.JLabel picturesLbl;
    private javax.swing.JComboBox<String> roomComboBox;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
