package view;

/**
 *
 * @author kappe
 */
public class InfoFrame extends javax.swing.JFrame {

    /**
     * Creates new form InfoFrame
     *
     * @param message
     */
    public InfoFrame(String message) {
        initComponents();

        textArea.setText(message);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        okBtn = new javax.swing.JButton();
        titleLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Informácie");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(204, 171, 244));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        okBtn.setBackground(new java.awt.Color(114, 14, 126));
        okBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        okBtn.setForeground(new java.awt.Color(255, 255, 255));
        okBtn.setText("<html>\n<p style=\"text-align: center;\">\nOK\n</p>\n</html>");
        okBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                okBtnMouseReleased(evt);
            }
        });
        mainPanel.add(okBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 110, 40));

        titleLbl.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 0, 0));
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("Informácie o ubytovaní");
        mainPanel.add(titleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 500, 50));

        textArea.setEditable(false);
        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        mainPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 430, 350));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void okBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okBtnMouseReleased
        this.dispose();
    }//GEN-LAST:event_okBtnMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton okBtn;
    private javax.swing.JTextArea textArea;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables

}
