package view;

import controller.MainLogic;
import controller.Tool;
import java.text.DecimalFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Accommodation;
import model.Payment;

/**
 *
 * @author kappe
 */
public class MakePaymentFrame extends javax.swing.JFrame {

    private final ShowUnpaidAccommodationsFrame parentFrame;
    private final MainLogic app;
    private final Accommodation accommodation;

    /**
     * Creates new form MakePaymentFrame
     *
     * @param parentFrame
     * @param accommodation
     */
    public MakePaymentFrame(ShowUnpaidAccommodationsFrame parentFrame, Accommodation accommodation) {
        initComponents();

        this.parentFrame = parentFrame;
        this.app = parentFrame.getParentFrame().app;
        this.accommodation = accommodation;

        initFields();
    }

    private void initFields() {
        clientFld.setText(accommodation.getClient().toString());
        roomFld.setText(accommodation.getRoom().getId());
        fromFld.setText(Tool.dateToString(accommodation.getFrom()));
        untilFld.setText(Tool.dateToString(accommodation.getUntil()));

        dateChooser.setDate(parentFrame.getParentFrame().getCurrentSystemTime().getTime());

        DecimalFormat formatter = new DecimalFormat("########0.00");
        accommodationPriceFld.setText(formatter.format(accommodation.getPrice()));
        servicePriceFld.setText(formatter.format(accommodation.getServicesPrice()));
        totalPriceFld.setText(formatter.format(accommodation.getTotalPrice()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        roomFld = new javax.swing.JTextField();
        clientFld = new javax.swing.JTextField();
        untilFld = new javax.swing.JTextField();
        fromFld = new javax.swing.JTextField();
        servicePriceFld = new javax.swing.JTextField();
        accommodationPriceFld = new javax.swing.JTextField();
        totalPriceFld = new javax.swing.JTextField();
        dateChooser = new com.toedter.calendar.JDateChooser();
        payBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        cashCheckBox = new javax.swing.JCheckBox();
        titleLbl = new javax.swing.JLabel();
        accommodationLbl = new javax.swing.JLabel();
        dateLbl = new javax.swing.JLabel();
        fromLbl = new javax.swing.JLabel();
        untilLbl = new javax.swing.JLabel();
        accommodationPriceLbl = new javax.swing.JLabel();
        servicePriceLbl = new javax.swing.JLabel();
        euroSignLbl0 = new javax.swing.JLabel();
        roomLbl = new javax.swing.JLabel();
        euroSignLbl1 = new javax.swing.JLabel();
        totalPriceLbl = new javax.swing.JLabel();
        euroSignLbl2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Zaplatiť za ubytovanie");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(204, 171, 244));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roomFld.setEditable(false);
        roomFld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mainPanel.add(roomFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 400, 30));

        clientFld.setEditable(false);
        clientFld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mainPanel.add(clientFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 400, 30));

        untilFld.setEditable(false);
        untilFld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mainPanel.add(untilFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 170, 30));

        fromFld.setEditable(false);
        fromFld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mainPanel.add(fromFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 170, 30));

        servicePriceFld.setEditable(false);
        servicePriceFld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        servicePriceFld.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        mainPanel.add(servicePriceFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 90, 30));

        accommodationPriceFld.setEditable(false);
        accommodationPriceFld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        accommodationPriceFld.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        mainPanel.add(accommodationPriceFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 90, 30));

        totalPriceFld.setEditable(false);
        totalPriceFld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalPriceFld.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        mainPanel.add(totalPriceFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 90, 30));
        mainPanel.add(dateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 170, -1));

        payBtn.setBackground(new java.awt.Color(114, 14, 126));
        payBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        payBtn.setForeground(new java.awt.Color(255, 255, 255));
        payBtn.setText("<html>\n<p style=\"text-align: center;\">\nZaplatiť\n</p>\n</html>");
        payBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                payBtnMouseReleased(evt);
            }
        });
        mainPanel.add(payBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 110, 40));

        backBtn.setBackground(new java.awt.Color(114, 14, 126));
        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("<html>\n<p style=\"text-align: center;\">\nSpäť\n</p>\n</html>");
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                backBtnMouseReleased(evt);
            }
        });
        mainPanel.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 110, 40));

        cashCheckBox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cashCheckBox.setForeground(new java.awt.Color(114, 14, 126));
        cashCheckBox.setText("Platba v hotovosti");
        mainPanel.add(cashCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 200, 30));

        titleLbl.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 0, 0));
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("Platba za pobyt a využité služby");
        mainPanel.add(titleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 700, 50));

        accommodationLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        accommodationLbl.setForeground(new java.awt.Color(144, 14, 126));
        accommodationLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        accommodationLbl.setText("Zákazník:");
        mainPanel.add(accommodationLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 150, 30));

        dateLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dateLbl.setForeground(new java.awt.Color(144, 14, 126));
        dateLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dateLbl.setText("Dátum platby:");
        mainPanel.add(dateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 150, 30));

        fromLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fromLbl.setForeground(new java.awt.Color(144, 14, 126));
        fromLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fromLbl.setText("Od:");
        mainPanel.add(fromLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 30, 30));

        untilLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        untilLbl.setForeground(new java.awt.Color(144, 14, 126));
        untilLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        untilLbl.setText("Do:");
        mainPanel.add(untilLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 30, 30));

        accommodationPriceLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        accommodationPriceLbl.setForeground(new java.awt.Color(144, 14, 126));
        accommodationPriceLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        accommodationPriceLbl.setText("Cena za ubytovanie:");
        mainPanel.add(accommodationPriceLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 180, 30));

        servicePriceLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        servicePriceLbl.setForeground(new java.awt.Color(144, 14, 126));
        servicePriceLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        servicePriceLbl.setText("Cena za služby:");
        mainPanel.add(servicePriceLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 150, 30));

        euroSignLbl0.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        euroSignLbl0.setForeground(new java.awt.Color(114, 14, 126));
        euroSignLbl0.setText("€");
        mainPanel.add(euroSignLbl0, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 30, 30));

        roomLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        roomLbl.setForeground(new java.awt.Color(144, 14, 126));
        roomLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        roomLbl.setText("Izba:");
        mainPanel.add(roomLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 150, 30));

        euroSignLbl1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        euroSignLbl1.setForeground(new java.awt.Color(114, 14, 126));
        euroSignLbl1.setText("€");
        mainPanel.add(euroSignLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 30, 30));

        totalPriceLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalPriceLbl.setForeground(new java.awt.Color(144, 14, 126));
        totalPriceLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalPriceLbl.setText("Celková cena:");
        mainPanel.add(totalPriceLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 150, 30));

        euroSignLbl2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        euroSignLbl2.setForeground(new java.awt.Color(114, 14, 126));
        euroSignLbl2.setText("€");
        mainPanel.add(euroSignLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 30, 30));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseReleased
        this.parentFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnMouseReleased

    private void payBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payBtnMouseReleased
        accommodation.setPaid(true);
        app.saveAccommodations();

        Date date = dateChooser.getDate();
        app.addPayment(new Payment(accommodation.getTotalPrice(), accommodation, cashCheckBox.isSelected(), date));
        parentFrame.resetAccommodationsTable();

        JOptionPane.showMessageDialog(null, "Platba bola zaznamenaná.");
        backBtnMouseReleased(null);
    }//GEN-LAST:event_payBtnMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accommodationLbl;
    private javax.swing.JTextField accommodationPriceFld;
    private javax.swing.JLabel accommodationPriceLbl;
    private javax.swing.JButton backBtn;
    private javax.swing.JCheckBox cashCheckBox;
    private javax.swing.JTextField clientFld;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JLabel euroSignLbl0;
    private javax.swing.JLabel euroSignLbl1;
    private javax.swing.JLabel euroSignLbl2;
    private javax.swing.JTextField fromFld;
    private javax.swing.JLabel fromLbl;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton payBtn;
    private javax.swing.JTextField roomFld;
    private javax.swing.JLabel roomLbl;
    private javax.swing.JTextField servicePriceFld;
    private javax.swing.JLabel servicePriceLbl;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JTextField totalPriceFld;
    private javax.swing.JLabel totalPriceLbl;
    private javax.swing.JTextField untilFld;
    private javax.swing.JLabel untilLbl;
    // End of variables declaration//GEN-END:variables
}
