package view;

import controller.MainLogic;
import controller.Tool;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Accommodation;
import model.Service;

/**
 *
 * @author kappe
 */
public class RegisterUsedServiceFrame extends javax.swing.JFrame {

    private final MainFrame parentFrame;
    private final MainLogic app;
    private final ArrayList<Accommodation> unpaidAccommodations;

    /**
     * Creates new form RegisterUsedServiceFrame
     *
     * @param parentFrame
     */
    public RegisterUsedServiceFrame(MainFrame parentFrame) {
        initComponents();

        this.parentFrame = parentFrame;
        this.app = parentFrame.app;
        this.unpaidAccommodations = parentFrame.app.getUnpaidAccommodations();

        populateAccommodationComboBox();
        populateServiceComboBox();

        dateChooser.setDate(parentFrame.getCurrentSystemTime().getTime());
    }

    private void populateAccommodationComboBox() {
        String[] accommodationsDetail = app.getUnpaidAccommodationsDetail(unpaidAccommodations);
        accommodationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(accommodationsDetail));

        if (accommodationComboBox.getModel().getSize() > 0) {
            accommodationComboBox.setSelectedIndex(0);
        }
    }

    private void populateServiceComboBox() {
        String[] services = app.getServicesDescription();
        serviceComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(services));

        if (serviceComboBox.getModel().getSize() > 0) {
            serviceComboBox.setSelectedIndex(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        accommodationComboBox = new javax.swing.JComboBox<>();
        serviceComboBox = new javax.swing.JComboBox<>();
        registerBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        priceFld = new javax.swing.JTextField();
        dateChooser = new com.toedter.calendar.JDateChooser();
        titleLbl = new javax.swing.JLabel();
        dateLbl = new javax.swing.JLabel();
        serviceLbl = new javax.swing.JLabel();
        roomLbl = new javax.swing.JLabel();
        dateLbl1 = new javax.swing.JLabel();
        euroSignLbl = new javax.swing.JLabel();
        fromLbl = new javax.swing.JLabel();
        fromFld = new javax.swing.JTextField();
        untilLbl = new javax.swing.JLabel();
        untilFld = new javax.swing.JTextField();
        roomLbl1 = new javax.swing.JLabel();
        roomFld = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Zaevidovanie využitej služby");
        setMinimumSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(204, 171, 244));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        accommodationComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        accommodationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2" }));
        accommodationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accommodationComboBoxActionPerformed(evt);
            }
        });
        mainPanel.add(accommodationComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 400, 30));

        serviceComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        serviceComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2" }));
        serviceComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceComboBoxActionPerformed(evt);
            }
        });
        mainPanel.add(serviceComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 400, 30));

        registerBtn.setBackground(new java.awt.Color(114, 14, 126));
        registerBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(255, 255, 255));
        registerBtn.setText("<html>\n<p style=\"text-align: center;\">\nZaevidovať\n</p>\n</html>");
        registerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                registerBtnMouseReleased(evt);
            }
        });
        mainPanel.add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 110, 40));

        backBtn.setBackground(new java.awt.Color(114, 14, 126));
        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("<html>\n<p style=\"text-align: center;\">\nSpäť\n</p>\n</html>");
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                backBtnMouseReleased(evt);
            }
        });
        mainPanel.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 110, 40));

        priceFld.setEditable(false);
        priceFld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        priceFld.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        mainPanel.add(priceFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 90, 30));
        mainPanel.add(dateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 180, -1));

        titleLbl.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 0, 0));
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("Zaevidovať využitú službu počas pobytu");
        mainPanel.add(titleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 700, 50));

        dateLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dateLbl.setForeground(new java.awt.Color(144, 14, 126));
        dateLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dateLbl.setText("Cena služby:");
        mainPanel.add(dateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 150, 30));

        serviceLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        serviceLbl.setForeground(new java.awt.Color(144, 14, 126));
        serviceLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        serviceLbl.setText("Využitá služba:");
        mainPanel.add(serviceLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 150, 30));

        roomLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        roomLbl.setForeground(new java.awt.Color(144, 14, 126));
        roomLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        roomLbl.setText("Ubytovanie:");
        mainPanel.add(roomLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 150, 30));

        dateLbl1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dateLbl1.setForeground(new java.awt.Color(144, 14, 126));
        dateLbl1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dateLbl1.setText("Dátum:");
        mainPanel.add(dateLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 150, 30));

        euroSignLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        euroSignLbl.setForeground(new java.awt.Color(114, 14, 126));
        euroSignLbl.setText("€");
        mainPanel.add(euroSignLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 190, 30));

        fromLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fromLbl.setForeground(new java.awt.Color(144, 14, 126));
        fromLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fromLbl.setText("Od:");
        mainPanel.add(fromLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 30, 30));

        fromFld.setEditable(false);
        fromFld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mainPanel.add(fromFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 170, 30));

        untilLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        untilLbl.setForeground(new java.awt.Color(144, 14, 126));
        untilLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        untilLbl.setText("Do:");
        mainPanel.add(untilLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 30, 30));

        untilFld.setEditable(false);
        untilFld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mainPanel.add(untilFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 170, 30));

        roomLbl1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        roomLbl1.setForeground(new java.awt.Color(144, 14, 126));
        roomLbl1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        roomLbl1.setText("Izba:");
        mainPanel.add(roomLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 150, 30));

        roomFld.setEditable(false);
        roomFld.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mainPanel.add(roomFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 400, 30));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseReleased
        this.parentFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnMouseReleased

    private void registerBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBtnMouseReleased
        int selectedAccommodationIndex = accommodationComboBox.getSelectedIndex();
        int selectedServiceIndex = serviceComboBox.getSelectedIndex();

        if (selectedAccommodationIndex < 0 || selectedServiceIndex < 0) {
            return;
        }

        Accommodation accommodation = unpaidAccommodations.get(selectedAccommodationIndex);
        Service service = app.getSelectedService(selectedServiceIndex);
        Date date = dateChooser.getDate();

        accommodation.addService(new Service(service.getPrice(), service.getDescription(), date));
        app.saveAccommodations();
        JOptionPane.showMessageDialog(null, "Služba bola zaznamenaná.");
    }//GEN-LAST:event_registerBtnMouseReleased

    private void serviceComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceComboBoxActionPerformed
        int index = serviceComboBox.getSelectedIndex();
        double price = app.getSelectedService(index).getPrice();

        priceFld.setText(new DecimalFormat("########0.00").format(price));
    }//GEN-LAST:event_serviceComboBoxActionPerformed

    private void accommodationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accommodationComboBoxActionPerformed
        int selectedAccommodationIndex = accommodationComboBox.getSelectedIndex();

        if (selectedAccommodationIndex < 0) {
            return;
        }

        Accommodation accommodation = unpaidAccommodations.get(selectedAccommodationIndex);
        roomFld.setText(accommodation.getRoom().getId());
        fromFld.setText(Tool.dateToString(accommodation.getFrom()));
        untilFld.setText(Tool.dateToString(accommodation.getUntil()));

    }//GEN-LAST:event_accommodationComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> accommodationComboBox;
    private javax.swing.JButton backBtn;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JLabel dateLbl1;
    private javax.swing.JLabel euroSignLbl;
    private javax.swing.JTextField fromFld;
    private javax.swing.JLabel fromLbl;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField priceFld;
    private javax.swing.JButton registerBtn;
    private javax.swing.JTextField roomFld;
    private javax.swing.JLabel roomLbl;
    private javax.swing.JLabel roomLbl1;
    private javax.swing.JComboBox<String> serviceComboBox;
    private javax.swing.JLabel serviceLbl;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JTextField untilFld;
    private javax.swing.JLabel untilLbl;
    // End of variables declaration//GEN-END:variables

}
