package view;

import controller.MainLogic;
import controller.Tool;
import java.awt.Color;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.Accommodation;

/**
 *
 * @author kappe
 */
public class ShowUnpaidAccommodationsFrame extends javax.swing.JFrame {

    private final MainFrame parentFrame;
    private final MainLogic app;

    /**
     * Creates new form ShowUnpaidAccommodationsFrame
     *
     * @param parentFrame
     */
    public ShowUnpaidAccommodationsFrame(MainFrame parentFrame) {
        initComponents();

        this.parentFrame = parentFrame;
        this.app = parentFrame.app;

        populateAccommodationsTable();
    }

    private void populateAccommodationsTable() {
        DefaultTableModel tblModel = (DefaultTableModel) accommodationsTbl.getModel();
        DecimalFormat formatter = new DecimalFormat("########0.00");

        ArrayList<Accommodation> accommodations = app.getEndedUnpaidAccommodations();
        for (int i = 0; i < accommodations.size(); i++) {
            Accommodation a = accommodations.get(i);

            String[] row = {a.getRoom().getId(), a.getClient().getName(), Tool.dateToString(a.getFrom()),
                Tool.dateToString(a.getUntil()), formatter.format(a.getTotalPrice()) + " €"};
            tblModel.addRow(row);
        }
    }

    public void resetAccommodationsTable() {
        DefaultTableModel tblModel = (DefaultTableModel) accommodationsTbl.getModel();
        tblModel.setRowCount(0);
        populateAccommodationsTable();
    }

    public MainFrame getParentFrame() {
        return parentFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        titleLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        accommodationsTbl = new javax.swing.JTable();
        payBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ukončené a nezaplatené ubytovania");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(204, 171, 244));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtn.setBackground(new java.awt.Color(114, 14, 126));
        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("<html>\n<p style=\"text-align: center;\">\nSpäť\n</p>\n</html>");
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                backBtnMouseReleased(evt);
            }
        });
        mainPanel.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 110, 40));

        titleLbl.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 0, 0));
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("Zoznam ukončených a nezaplatených pobytov");
        mainPanel.add(titleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 700, 50));

        accommodationsTbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        accommodationsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Izba", "Zákazník", "Dátum od", "Dátum do", "Cena"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        accommodationsTbl.setRowHeight(20);
        accommodationsTbl.setSelectionBackground(new java.awt.Color(204, 0, 204));
        accommodationsTbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(accommodationsTbl);
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setHorizontalAlignment(JLabel.CENTER);
        headerRenderer.setBackground(new Color(114, 14, 126));
        headerRenderer.setForeground(new Color(255, 255, 255));

        for (int i = 0; i < accommodationsTbl.getModel().getColumnCount(); i++) {
            accommodationsTbl.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }

        mainPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 650, 280));

        payBtn.setBackground(new java.awt.Color(114, 14, 126));
        payBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        payBtn.setForeground(new java.awt.Color(255, 255, 255));
        payBtn.setText("<html>\n<p style=\"text-align: center;\">\nZaplatiť\n</p>\n</html>");
        payBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                payBtnMouseReleased(evt);
            }
        });
        mainPanel.add(payBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 110, 40));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseReleased
        this.parentFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnMouseReleased

    private void payBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payBtnMouseReleased
        int index = accommodationsTbl.getSelectedRow();

        if (index < 0) {
            JOptionPane.showMessageDialog(null, "Vyberte záznam o ubytovaní.", "Chýba záznam!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Accommodation accommodation = app.getEndedUnpaidAccommodations().get(index);

        new MakePaymentFrame(this, accommodation).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_payBtnMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable accommodationsTbl;
    private javax.swing.JButton backBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton payBtn;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
