/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DataSerializer;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Company;

/**
 *
 * @author kappe
 */
public class AddCompanyFrame extends javax.swing.JFrame {

    JFrame parentFrame;
    private final ArrayList<Company> companies;

    /**
     * Creates new form AddCompany
     *
     * @param parent
     * @param companies
     */
    public AddCompanyFrame(JFrame parent, ArrayList<Company> companies) {
        initComponents();

        this.parentFrame = parent;
        this.companies = companies;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        countLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        businessLabel = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        businessField = new javax.swing.JTextField();
        countField = new javax.swing.JTextField();
        logoField = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        selectBtn = new javax.swing.JButton();
        logoImageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pridať zamestnávateľa");
        setMinimumSize(new java.awt.Dimension(680, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(253, 247, 236));
        mainPanel.setMinimumSize(new java.awt.Dimension(680, 500));
        mainPanel.setPreferredSize(new java.awt.Dimension(700, 520));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Vyplňte údaje o novom zamestnávateľovi");
        mainPanel.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 680, 40));

        countLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        countLabel.setForeground(new java.awt.Color(255, 153, 0));
        countLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        countLabel.setText("Počet zamestnancov:");
        mainPanel.add(countLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 150, 30));

        nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 153, 0));
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nameLabel.setText("Názov zamestnávateľa:");
        mainPanel.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 180, 30));

        businessLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        businessLabel.setForeground(new java.awt.Color(255, 153, 0));
        businessLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        businessLabel.setText("Oblasť podnikania:");
        mainPanel.add(businessLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 180, 30));

        logoLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logoLabel.setForeground(new java.awt.Color(255, 153, 0));
        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        logoLabel.setText("Logo:");
        mainPanel.add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 50, 30));

        nameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mainPanel.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 280, 30));

        businessField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mainPanel.add(businessField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 280, 30));

        countField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        countField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        mainPanel.add(countField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 110, 30));

        logoField.setEditable(false);
        logoField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        logoField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        mainPanel.add(logoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 280, 30));

        addBtn.setBackground(new java.awt.Color(255, 204, 102));
        addBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addBtn.setText("Pridať");
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                addBtnMouseReleased(evt);
            }
        });
        mainPanel.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 90, 40));

        cancelBtn.setBackground(new java.awt.Color(255, 204, 102));
        cancelBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelBtn.setText("Späť");
        cancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cancelBtnMouseReleased(evt);
            }
        });
        mainPanel.add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 90, 40));

        selectBtn.setBackground(new java.awt.Color(255, 204, 102));
        selectBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectBtn.setText("Vybrať");
        selectBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                selectBtnMouseReleased(evt);
            }
        });
        mainPanel.add(selectBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 80, 30));
        mainPanel.add(logoImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 170, 160));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseReleased
        if (nameField.getText().isBlank() || businessField.getText().isBlank()
                || countField.getText().isBlank() || logoField.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Prosím vyplňte všetky informácie!", "Chyba", JOptionPane.ERROR_MESSAGE);
        } else {
            String name = nameField.getText().trim();
            String business = businessField.getText().trim();
            int count;
            String path = logoField.getText();
            ImageIcon logo = new ImageIcon(path);

            try {
                count = Integer.parseInt(countField.getText().trim());
                if (count < 0) {
                    throw new NumberFormatException();
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Počet zamestnancov musí byť kladná číselná hodnota!", "Chyba", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Company company = new Company(name, business, count, logo);
            companies.add(company);
            DataSerializer.saveCompaniesToFile(companies, DataSerializer.COMPANIES_FILE);

            JOptionPane.showMessageDialog(null, "Údaje o novom programátorovi boli úspešne uložené!");
            dispose();
            parentFrame.setVisible(true);
        }
    }//GEN-LAST:event_addBtnMouseReleased

    private void cancelBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseReleased
        dispose();
        parentFrame.setVisible(true);
    }//GEN-LAST:event_cancelBtnMouseReleased

    private void selectBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectBtnMouseReleased
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        chooser.showOpenDialog(this);

        File f = chooser.getSelectedFile();
        if (f == null) {
            return;
        }

        if (f.getName().endsWith(".jpg") || f.getName().endsWith(".png")) {
            String path = f.getAbsolutePath();
            logoField.setText(path);
            ImageIcon logo = new ImageIcon(path);

            Image img = logo.getImage();
            Image imgScale = img.getScaledInstance(logoImageLabel.getWidth(), logoImageLabel.getHeight(), Image.SCALE_SMOOTH);
            logoImageLabel.setIcon(new ImageIcon(imgScale));
        } else {
            JOptionPane.showMessageDialog(null, "Prosím vyberte súbor typu jpg alebo png.", "Chyba", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_selectBtnMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField businessField;
    private javax.swing.JLabel businessLabel;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField countField;
    private javax.swing.JLabel countLabel;
    private javax.swing.JTextField logoField;
    private javax.swing.JLabel logoImageLabel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton selectBtn;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
