/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DataSerializer;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.Administrator;
import model.Company;
import model.Freelancer;
import model.Programmer;
import model.RentalRecord;
import model.SecurityConsultant;

/**
 *
 * @author kappe
 */
public class DeleteRentalRecordFrame extends javax.swing.JFrame {

    JFrame parentFrame;
    private final ArrayList<Programmer> programmers;
    private final ArrayList<SecurityConsultant> consultants;
    private final ArrayList<Administrator> administrators;
    private final ArrayList<Company> companies;
    private final ArrayList<RentalRecord> records;

    /**
     * Creates new form DeleteRentalRecordFrame
     *
     * @param parent
     * @param programmers
     * @param consultants
     * @param administrators
     * @param companies
     * @param records
     */
    public DeleteRentalRecordFrame(JFrame parent, ArrayList<Programmer> programmers, ArrayList<SecurityConsultant> consultants,
            ArrayList<Administrator> administrators, ArrayList<Company> companies, ArrayList<RentalRecord> records) {
        initComponents();

        this.parentFrame = parent;
        this.programmers = programmers;
        this.consultants = consultants;
        this.administrators = administrators;
        this.companies = companies;
        this.records = records;

        initTable();
    }

    private void initTable() {
        ((DefaultTableCellRenderer) recordsTable.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        DefaultTableModel tblModel = (DefaultTableModel) recordsTable.getModel();

        for (int i = 0; i < records.size(); i++) {
            RentalRecord r = records.get(i);
            String[] row = {r.getEmployer().getName(), r.getFreelancerNames()};
            tblModel.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        mainLabel = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        recordsTable = new javax.swing.JTable();
        cancelBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Zrušiť záznam o prenájme");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(253, 247, 236));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mainLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainLabel.setText("Vyberte záznam o prenájme, ktorý chcete zrušiť");
        mainPanel.add(mainLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 700, 40));

        cancelBtn.setBackground(new java.awt.Color(255, 204, 102));
        cancelBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelBtn.setText("Späť");
        cancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cancelBtnMouseReleased(evt);
            }
        });
        mainPanel.add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 100, 40));

        recordsTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        recordsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Zamestnáveteľ", "Prenajatý špecialisti"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        recordsTable.setRowHeight(22);
        recordsTable.setSelectionBackground(new java.awt.Color(255, 153, 51));
        jScrollPane1.setViewportView(recordsTable);

        mainPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 650, 280));

        cancelBtn1.setBackground(new java.awt.Color(255, 204, 102));
        cancelBtn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelBtn1.setText("Odstrániť");
        cancelBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cancelBtn1MouseReleased(evt);
            }
        });
        mainPanel.add(cancelBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 100, 40));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseReleased
        dispose();
        parentFrame.setVisible(true);
    }//GEN-LAST:event_cancelBtnMouseReleased

    private void cancelBtn1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtn1MouseReleased
        int selectedIndex = recordsTable.getSelectedRow();

        if (selectedIndex < 0) {
            return;
        }

        RentalRecord record = records.get(selectedIndex);
        record.getFreelancers().forEach(f -> {
            f.setAvailable(true);
        });

        for (Freelancer f : record.getFreelancers()) {
            for (Programmer p : programmers) {
                if (f == p) {
                    p.setAvailable(true);
                    break;
                }
            }
            for (SecurityConsultant c : consultants) {
                if (f == c) {
                    c.setAvailable(true);
                    break;
                }
            }
            for (Administrator a : administrators) {
                if (f == a) {
                    a.setAvailable(true);
                    break;
                }
            }
        }

        Company employer = record.getEmployer();
        employer.setEmployeeCount(employer.getEmployeeCount() - record.getFreelancers().size());

        records.remove(selectedIndex);
        DataSerializer.SaveAllModels(programmers, consultants, administrators, companies, records);
        JOptionPane.showMessageDialog(null, "Záznam bol úspešne odstránený.");

        dispose();
        parentFrame.setVisible(true);
    }//GEN-LAST:event_cancelBtn1MouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton cancelBtn1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTable recordsTable;
    // End of variables declaration//GEN-END:variables
}
