/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DataSerializer;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Company;

/**
 *
 * @author kappe
 */
public class DeleteCompanyFrame extends javax.swing.JFrame {

    JFrame parentFrame;
    private final ArrayList<Company> companies;

    /**
     * Creates new form DeleteCompanyFrame
     *
     * @param parent
     * @param companies
     */
    public DeleteCompanyFrame(JFrame parent, ArrayList<Company> companies) {
        initComponents();

        this.parentFrame = parent;
        this.companies = companies;

        populateCompaniesList();
    }

    private void populateCompaniesList() {
        DefaultListModel<String> lst = new DefaultListModel<>();
        for (int i = 0; i < companies.size(); i++) {
            lst.add(i, companies.get(i).getName());
        }
        companiesList.setModel(lst);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        logoImageLabel = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();
        countLabel = new javax.swing.JLabel();
        businessLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        businessField = new javax.swing.JTextField();
        countField = new javax.swing.JTextField();
        cancelBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        companiesList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Odstrániť zamestnávateľa");
        setMinimumSize(new java.awt.Dimension(680, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(253, 247, 236));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Zoznam zamestnávateľov");
        mainPanel.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 680, 40));
        mainPanel.add(logoImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 170, 160));

        logoLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logoLabel.setForeground(new java.awt.Color(255, 153, 51));
        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        logoLabel.setText("Logo:");
        mainPanel.add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 60, 30));

        countLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        countLabel.setForeground(new java.awt.Color(255, 153, 51));
        countLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        countLabel.setText("Počet zamestnancov:");
        mainPanel.add(countLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 160, 30));

        businessLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        businessLabel.setForeground(new java.awt.Color(255, 153, 51));
        businessLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        businessLabel.setText("Oblasť podnikania:");
        mainPanel.add(businessLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 160, 30));

        nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 153, 51));
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nameLabel.setText("Názov zamestnávateľa:");
        mainPanel.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 160, 30));

        nameField.setEditable(false);
        nameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mainPanel.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 260, 30));

        businessField.setEditable(false);
        businessField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mainPanel.add(businessField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 260, 30));

        countField.setEditable(false);
        countField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        countField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        mainPanel.add(countField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 100, 30));

        cancelBtn.setBackground(new java.awt.Color(255, 204, 102));
        cancelBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelBtn.setText("Späť");
        cancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cancelBtnMouseReleased(evt);
            }
        });
        mainPanel.add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 100, 40));

        deleteBtn.setBackground(new java.awt.Color(255, 204, 102));
        deleteBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteBtn.setText("Odstrániť");
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                deleteBtnMouseReleased(evt);
            }
        });
        mainPanel.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 100, 40));

        companiesList.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        companiesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        companiesList.setSelectionBackground(new java.awt.Color(255, 153, 51));
        companiesList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                companiesListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(companiesList);

        mainPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 150, 330));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseReleased
        dispose();
        parentFrame.setVisible(true);
    }//GEN-LAST:event_cancelBtnMouseReleased

    private void deleteBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseReleased
        int selectedIndex = companiesList.getSelectedIndex();
        if (selectedIndex > -1) {
            companies.remove(selectedIndex);
            DataSerializer.saveCompaniesToFile(companies, DataSerializer.COMPANIES_FILE);
            JOptionPane.showMessageDialog(null, "Zamestnávateľ bol úspešne odstránený.");
            dispose();
            parentFrame.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Prosím vyberte si jedného zamestnávateľa zo zoznamu, ktorého chcete odstrániť!");
        }
    }//GEN-LAST:event_deleteBtnMouseReleased

    private void companiesListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_companiesListValueChanged
        int selectedIndex = companiesList.getSelectedIndex();

        if (selectedIndex > -1) {
            Company company = companies.get(selectedIndex);
            nameField.setText(company.getName());
            businessField.setText(company.getBusinessArea());
            countField.setText(String.valueOf(company.getEmployeeCount()));
            Image img = company.getLogo().getImage();
            Image imgScale = img.getScaledInstance(logoImageLabel.getWidth(), logoImageLabel.getHeight(), Image.SCALE_SMOOTH);
            logoImageLabel.setIcon(new ImageIcon(imgScale));
        }
    }//GEN-LAST:event_companiesListValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField businessField;
    private javax.swing.JLabel businessLabel;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JList<String> companiesList;
    private javax.swing.JTextField countField;
    private javax.swing.JLabel countLabel;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logoImageLabel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
