/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DataSerializer;
import java.util.ArrayList;
import javax.swing.JFrame;
import model.*;

/**
 *
 * @author kappe
 */
public class HomeFrame extends javax.swing.JFrame {

    private final ArrayList<Programmer> programmers;
    private final ArrayList<SecurityConsultant> consultants;
    private final ArrayList<Administrator> administrators;
    private final ArrayList<Company> companies;
    private final ArrayList<RentalRecord> records;

    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() {
        initComponents();

        programmers = DataSerializer.loadProgrammersFromFile(DataSerializer.PROGRAMMERS_FILE);
        consultants = DataSerializer.loadConsultantsFromFile(DataSerializer.CONSULTANTS_FILE);
        administrators = DataSerializer.loadAdministratorsFromFile(DataSerializer.ADMINISTRATORS_FILE);
        companies = DataSerializer.loadCompaniesFromFile(DataSerializer.COMPANIES_FILE);
        records = DataSerializer.loadRecordsFromFile(DataSerializer.RECORDS_FILE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        addSpecialistBtn = new javax.swing.JButton();
        deleteSpecialistsBtn = new javax.swing.JButton();
        addCompanyBtn = new javax.swing.JButton();
        deleteCompaniesBtn = new javax.swing.JButton();
        createRentBtn = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        logoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IT profesia");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(253, 247, 236));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addSpecialistBtn.setBackground(new java.awt.Color(255, 204, 102));
        addSpecialistBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addSpecialistBtn.setText("<html>\n<p style=\"text-align: center;\">\nPridať<br>špecialistu\n</p></html>");
        addSpecialistBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addSpecialistBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                addSpecialistBtnMouseReleased(evt);
            }
        });
        mainPanel.add(addSpecialistBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 160, 110));

        deleteSpecialistsBtn.setBackground(new java.awt.Color(255, 204, 102));
        deleteSpecialistsBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteSpecialistsBtn.setText("<html>\n<p style=\"text-align: center;\">\nOdstrániť<br>špecialistu\n</p></html>");
        deleteSpecialistsBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteSpecialistsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                deleteSpecialistsBtnMouseReleased(evt);
            }
        });
        mainPanel.add(deleteSpecialistsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 160, 110));

        addCompanyBtn.setBackground(new java.awt.Color(255, 204, 102));
        addCompanyBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addCompanyBtn.setText("<html>\n<p style=\"text-align: center;\">\nPridať<br>zamestnávateľa\n</p></html>");
        addCompanyBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addCompanyBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                addCompanyBtnMouseReleased(evt);
            }
        });
        mainPanel.add(addCompanyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 160, 110));

        deleteCompaniesBtn.setBackground(new java.awt.Color(255, 204, 102));
        deleteCompaniesBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteCompaniesBtn.setText("<html>\n<p style=\"text-align: center;\">\nOdstrániť<br>zamestnávateľa\n</p></html>");
        deleteCompaniesBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteCompaniesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                deleteCompaniesBtnMouseReleased(evt);
            }
        });
        mainPanel.add(deleteCompaniesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 160, 110));

        createRentBtn.setBackground(new java.awt.Color(255, 204, 102));
        createRentBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        createRentBtn.setText("<html>\n<p style=\"text-align: center;\">\nVytvoriť záznam<br>o prenájme\n</p></html>");
        createRentBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        createRentBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                createRentBtnMouseReleased(evt);
            }
        });
        mainPanel.add(createRentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 160, 110));

        jButton6.setBackground(new java.awt.Color(255, 204, 102));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setText("<html>\n<p style=\"text-align: center;\">\nZrušiť záznam<br>o prenájme\n</p></html>");
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton6MouseReleased(evt);
            }
        });
        mainPanel.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 160, 110));

        jButton7.setBackground(new java.awt.Color(255, 204, 102));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton7.setText("<html>\n<p style=\"text-align: center;\">\nZobraziť detailný<br>prehľad informácií\n</p></html>");
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton7MouseReleased(evt);
            }
        });
        mainPanel.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 160, 110));

        jButton8.setBackground(new java.awt.Color(255, 204, 102));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton8.setText("<html>\n<p style=\"text-align: center;\">\nUkončiť aplikáciu\n</p></html>");
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton8MouseReleased(evt);
            }
        });
        mainPanel.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, 160, 110));

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/IT-profesia-logo.png"))); // NOI18N
        mainPanel.add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addSpecialistBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addSpecialistBtnMouseReleased
        JFrame specialistFrame = new AddSpecialistFrame(this, programmers, consultants, administrators);
        this.setVisible(false);
        specialistFrame.setVisible(true);
    }//GEN-LAST:event_addSpecialistBtnMouseReleased

    private void deleteSpecialistsBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteSpecialistsBtnMouseReleased
        JFrame specialistFrame = new DeleteSpecialistFrame(this, programmers, consultants, administrators);
        this.setVisible(false);
        specialistFrame.setVisible(true);
    }//GEN-LAST:event_deleteSpecialistsBtnMouseReleased

    private void addCompanyBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCompanyBtnMouseReleased
        JFrame companyFrame = new AddCompanyFrame(this, companies);
        this.setVisible(false);
        companyFrame.setVisible(true);
    }//GEN-LAST:event_addCompanyBtnMouseReleased

    private void deleteCompaniesBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteCompaniesBtnMouseReleased
        JFrame companyFrame = new DeleteCompanyFrame(this, companies);
        this.setVisible(false);
        companyFrame.setVisible(true);
    }//GEN-LAST:event_deleteCompaniesBtnMouseReleased

    private void createRentBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createRentBtnMouseReleased
        JFrame recordFrame = new AddRentalRecordFrame(this, programmers, consultants, administrators, companies, records);
        this.setVisible(false);
        recordFrame.setVisible(true);
    }//GEN-LAST:event_createRentBtnMouseReleased

    private void jButton6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseReleased
        JFrame recordFrame = new DeleteRentalRecordFrame(this, programmers, consultants, administrators, companies, records);
        this.setVisible(false);
        recordFrame.setVisible(true);
    }//GEN-LAST:event_jButton6MouseReleased

    private void jButton7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseReleased
        JFrame recordFrame = new InfoFrame(this, programmers, consultants, administrators, companies, records);
        this.setVisible(false);
        recordFrame.setVisible(true);
    }//GEN-LAST:event_jButton7MouseReleased

    private void jButton8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseReleased
        dispose();
        System.exit(0);
    }//GEN-LAST:event_jButton8MouseReleased

    /**
     * @param args the command line arguments
     */
    public void runGUI(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new HomeFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCompanyBtn;
    private javax.swing.JButton addSpecialistBtn;
    private javax.swing.JButton createRentBtn;
    private javax.swing.JButton deleteCompaniesBtn;
    private javax.swing.JButton deleteSpecialistsBtn;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
