/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.JFrame;
import model.*;

/**
 *
 * @author kappe
 */
public class InfoFrame extends javax.swing.JFrame {

    JFrame parentFrame;
    private final ArrayList<Programmer> programmers;
    private final ArrayList<SecurityConsultant> consultants;
    private final ArrayList<Administrator> administrators;
    private final ArrayList<Company> companies;
    private final ArrayList<RentalRecord> records;

    /**
     * Creates new form InfoFrame
     *
     * @param parent
     * @param programmers
     * @param consultants
     * @param administrators
     * @param companies
     * @param records
     */
    public InfoFrame(JFrame parent, ArrayList<Programmer> programmers, ArrayList<SecurityConsultant> consultants,
            ArrayList<Administrator> administrators, ArrayList<Company> companies, ArrayList<RentalRecord> records) {
        initComponents();

        this.parentFrame = parent;
        this.programmers = programmers;
        this.consultants = consultants;
        this.administrators = administrators;
        this.companies = companies;
        this.records = records;

        initLabels();
    }

    private void initLabels() {
        int programmerCount = 0;
        int consultantCount = 0;
        int adminCount = 0;

        programmerCount = programmers.stream().filter(p -> (p.isAvailable())).map(_item -> 1).reduce(programmerCount, Integer::sum);
        consultantCount = consultants.stream().filter(p -> (p.isAvailable())).map(_item -> 1).reduce(consultantCount, Integer::sum);
        adminCount = administrators.stream().filter(p -> (p.isAvailable())).map(_item -> 1).reduce(adminCount, Integer::sum);

        allProgrammersLabel.setText("Počet programátorov: " + programmers.size());
        allConsultantsLabel.setText("Počet bezpečnostných konzultantov: " + consultants.size());
        allAdminsLabel.setText("Počet administrátorov: " + administrators.size());
        allCompaniesLabel.setText("Počet zamestnávateľov: " + companies.size());

        freeProgrammerLabel.setText("Z toho voľných: " + programmerCount);
        freeConsultantLabel.setText("Z toho voľných: " + consultantCount);
        freeAdminLabel.setText("Z toho voľných: " + adminCount);
        rentLabel.setText("Počet prenájmov: " + records.size());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        mainLabel = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        freeProgrammerLabel = new javax.swing.JLabel();
        freeConsultantLabel = new javax.swing.JLabel();
        freeAdminLabel = new javax.swing.JLabel();
        allCompaniesLabel = new javax.swing.JLabel();
        allAdminsLabel = new javax.swing.JLabel();
        allConsultantsLabel = new javax.swing.JLabel();
        allProgrammersLabel = new javax.swing.JLabel();
        rentLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(253, 247, 236));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mainLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainLabel.setText("<html>\n<p style=\"text-align: center;\">\nInformácie o evidovaných<br>zamestnávateľoch a špecialistoch\n</p>\n</html>");
        mainPanel.add(mainLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 600, 70));

        cancelBtn.setBackground(new java.awt.Color(255, 204, 102));
        cancelBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelBtn.setText("Späť");
        cancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cancelBtnMouseReleased(evt);
            }
        });
        mainPanel.add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 100, 40));

        freeProgrammerLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        freeProgrammerLabel.setForeground(new java.awt.Color(255, 153, 51));
        freeProgrammerLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        freeProgrammerLabel.setText("Z toho voľných:");
        mainPanel.add(freeProgrammerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 180, 40));

        freeConsultantLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        freeConsultantLabel.setForeground(new java.awt.Color(255, 153, 51));
        freeConsultantLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        freeConsultantLabel.setText("Z toho voľných:");
        mainPanel.add(freeConsultantLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 180, 40));

        freeAdminLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        freeAdminLabel.setForeground(new java.awt.Color(255, 153, 51));
        freeAdminLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        freeAdminLabel.setText("Z toho voľných:");
        mainPanel.add(freeAdminLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 180, 40));

        allCompaniesLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        allCompaniesLabel.setForeground(new java.awt.Color(255, 153, 51));
        allCompaniesLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        allCompaniesLabel.setText("Počet zamestnávateľov:");
        mainPanel.add(allCompaniesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 300, 40));

        allAdminsLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        allAdminsLabel.setForeground(new java.awt.Color(255, 153, 51));
        allAdminsLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        allAdminsLabel.setText("Počet administrátorov:");
        mainPanel.add(allAdminsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 300, 40));

        allConsultantsLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        allConsultantsLabel.setForeground(new java.awt.Color(255, 153, 51));
        allConsultantsLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        allConsultantsLabel.setText("Počet bezpečnostných konzultantov:");
        mainPanel.add(allConsultantsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 300, 40));

        allProgrammersLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        allProgrammersLabel.setForeground(new java.awt.Color(255, 153, 51));
        allProgrammersLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        allProgrammersLabel.setText("Počet programátorov:");
        mainPanel.add(allProgrammersLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 300, 40));

        rentLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        rentLabel.setForeground(new java.awt.Color(255, 153, 51));
        rentLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rentLabel.setText("Počet prenájmov:");
        mainPanel.add(rentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 180, 40));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseReleased
        dispose();
        parentFrame.setVisible(true);
    }//GEN-LAST:event_cancelBtnMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel allAdminsLabel;
    private javax.swing.JLabel allCompaniesLabel;
    private javax.swing.JLabel allConsultantsLabel;
    private javax.swing.JLabel allProgrammersLabel;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel freeAdminLabel;
    private javax.swing.JLabel freeConsultantLabel;
    private javax.swing.JLabel freeProgrammerLabel;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel rentLabel;
    // End of variables declaration//GEN-END:variables
}
